# Generated by Django 5.0.2 on 2024-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='#502787', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='initials',
            field=models.CharField(default='EM', max_length=5),
            preserve_default=False,
        ),
    ]
